---
title: "CSYC Exploration"
output:
  html_document:
    df_print: paged
---

Reviewing positional information to discover the start time

```{r load data}
#load & format expedition data
rm(list=ls())


#library
library(tidyverse)
library(dplyr)
library(zoo)

dat_folder <- "../data"

dat_files <- list.files(dat_folder, full.names = TRUE)

exp <- lapply(dat_files, read.csv, stringsAsFactors=FALSE)
exp_raw <- do.call(rbind, exp)

#remove any columns where the data is entirely NA
allna <- which(apply(exp_raw, 2, function(x) all(is.na(x))))   #Find columns where all is not NA

exp <- exp_raw %>% select(-allna)

#Convert Time
exp$time <- as.POSIXct((exp$Utc) * (60*60*24), origin = "1899-12-30", tz = "America/Detroit")

#Select only needed columns
exp <- exp %>% select(time, Bsp, Awa, Aws, Twa, Tws, Twd, Hdg, PDOP, GeoSep, Lat, Lon, Cog, Sog, GPS.time, Twd.90, Mk.Lat, Mk.Lon, Stbd.lat, Stbd.lon)

#change names to lowercase for easier handling
names(exp) <- tolower(names(exp))


```

```{r}

ggplot(exp) + geom_path(aes(x=lon, y=lat), color="blue") + geom_point(aes(x=mk.lon, y=mk.lat))

```

, label = ~htmlEscape(time)
```{r}
library(leaflet)
library(htmltools)

timeformatted <- format(exp$time, "%R")

exp_l <- exp[exp$time > as.POSIXct("2018-08-25 12:55:00 EDT"), ]

pal <- colorNumeric(
  palette = "Blues",
  domain = exp_l$sog)

leaflet(exp_l) %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addPolylines(lng=~lon, lat= ~lat, label = ~htmlEscape(sog), color= ~ pal(sog))
  

```



